function fwmodel = initFwmodel(handles, argExtern)

if ~exist('argExtern','var')
    argExtern={};
end

if ~exist('fw','dir')
    mkdir('fw');
end

fwmodel = struct(...
      'name', 'fwmodel', ...
      'pathname', '', ...
      'handles',[],...
      'mc_rootpath','', ...
      'mc_exepath','', ...
      'mc_appname','', ...
      'mc_exename', '', ...
      'mc_exename_ext', '', ...
      'mc_options', '', ...
      'nphotons',1e6, ...
      'timegates',[0 5e-9 5e-9],...
      'nWavelengths',1, ...
      'tiss_prop',struct([]), ...
      'Ch',[], ...
      'cmThreshold',[], ...
      'cmThresholdFluence',[-3, -1], ...
      'headvol',initHeadvol(), ...
      'mesh',initMesh(), ...
      'mesh_scalp',initMesh(), ...
      'errMCoutput',[], ...
      'Adot',[], ...
      'Adot_scalp',[], ...
      'AdotDate',struct('num',0), ...
      'AdotVolFlag',0, ...
      'projVoltoMesh_brain', '', ...
      'projVoltoMesh_scalp', '', ...
      'colormin',[.74 .47 .40], ...
      'fluenceProfFnames',{[]}, ...
      'fluenceProf',repmat(initFluenceProf(), 2,1), ...
      'nFluenceProfPerFile', 50, ...
      'MNI_inMCspace', [0, 0, 0],...
      'normalizeFluence', true, ...
      'axes',[], ...
      'center',[], ...
      'orientation', '', ...
      'checkCompatability',[], ...
      'isempty',@isempty_loc, ...      
      'prepObjForSave',[] ...
);

% Set handles specific to the current GUI
if ~isempty(handles)
    if ishandles(handles.output)
        guiname = get(handles.output, 'tag');
        if strcmpi(guiname, 'AtlasViewerGUI')
            fwmodel = setAtlasViewerGUI(fwmodel, handles);
        elseif strcmpi(guiname, 'brainScape')
            fwmodel = setBrainscape(fwmodel, handles);
        end
    end
end


% Find MC application 
fwmodel = findMCapp(fwmodel, argExtern);

% Set MC options based on app type
fwmodel = setMCoptions(fwmodel);




% ----------------------------------------------------------------------------
function fwmodel = setAtlasViewerGUI(fwmodel, handles)

ENABLE_FLUENCE_PROF=0;

fwmodel.handles = struct(...
    'surf',[], ...
    'hLighting',[], ...
    'editSelectChannelSensitivity_nwe',[], ...
    'textSelectChannelSensitivity_new',[], ...
    'editSensitivityColormapThreshold_new',[], ...
    'textSensitivityColormapThreshold_new',[], ...
    'menuItemGenerateLoadSensitivityProfile',[], ...
    'menuItemGenerateMCInput',[], ...
    'menuItemEnableSensitivityMatrixVolume',[], ...
    'menuItemGenFluenceProfile',[], ....
    'menuItemLoadPrecalculatedProfile',[], ...
    'menuItemGetSensitivityatMNICoordinates',[], ...
    'popupmenuImageDisplay',[], ...
    'colorbar',[], ...
    'menuItemImageReconGUI', [] ...
    );
fwmodel.handles.editSelectChannelSensitivity_new = handles.editSelectChannelSensitivity_new;
fwmodel.handles.textSelectChannelSensitivity_new =  handles.textSelectChannelSensitivity_new;
fwmodel.handles.editSensitivityColormapThreshold_new = handles.editSensitivityColormapThreshold_new;
fwmodel.handles.textSensitivityColormapThreshold_new = handles.textSensitivityColormapThreshold_new;
fwmodel.handles.menuItemGenerateLoadSensitivityProfile = handles.menuItemGenerateLoadSensitivityProfile;
fwmodel.handles.menuItemGenerateMCInput = handles.menuItemGenerateMCInput;
fwmodel.handles.menuItemEnableSensitivityMatrixVolume = handles.menuItemEnableSensitivityMatrixVolume;
fwmodel.handles.menuItemGenFluenceProfile = handles.menuItemGenFluenceProfile;
fwmodel.handles.menuItemLoadPrecalculatedProfile = handles.menuItemLoadPrecalculatedProfile;
fwmodel.handles.popupmenuImageDisplay = handles.popupmenuImageDisplay;
fwmodel.handles.menuItemGetSensitivityatMNICoordinates = handles.menuItemGetSensitivityatMNICoordinates;

% Need image recon handle in order to enable it when Adot is present
fwmodel.handles.menuItemImageReconGUI = handles.menuItemImageReconGUI;

fwmodel.handles.axes = handles.axesSurfDisplay;

set(handles.menuItemEnableSensitivityMatrixVolume,'enable','off');

set(fwmodel.handles.editSelectChannelSensitivity_new,'enable','off');
set(fwmodel.handles.textSelectChannelSensitivity_new,'enable','off');
set(fwmodel.handles.editSelectChannelSensitivity_new,'string','0 0');

set(fwmodel.handles.editSensitivityColormapThreshold_new,'enable','off');
set(fwmodel.handles.textSensitivityColormapThreshold_new,'enable','off');
set(fwmodel.handles.editSensitivityColormapThreshold_new,'string','-2 0');

set(fwmodel.handles.menuItemGenerateLoadSensitivityProfile,'enable','off');
set(fwmodel.handles.menuItemGenerateMCInput,'enable','off');

set(fwmodel.handles.menuItemGenFluenceProfile,'enable','off');
if ENABLE_FLUENCE_PROF
    set(fwmodel.handles.menuItemGenFluenceProfile,'visible','on');
end
set(fwmodel.handles.menuItemLoadPrecalculatedProfile,'enable','off');

set(fwmodel.handles.popupmenuImageDisplay,'enable','off');
set(fwmodel.handles.popupmenuImageDisplay,'value',1);

set(fwmodel.handles.menuItemGetSensitivityatMNICoordinates,'enable','off');

fwmodel.Ch          = str2num(get(fwmodel.handles.editSelectChannelSensitivity_new,'string'));
fwmodel.cmThreshold = str2num(get(fwmodel.handles.editSensitivityColormapThreshold_new,'string'));




% ----------------------------------------------------------------------------
function fwmodel = setBrainscape(fwmodel, handles)

fwmodel.handles = struct(...
    'surf', [], ...
    'textSelectChannelSensitivity', [], ...
    'editSelectChannelSensitivity', [] ...
    );
fwmodel.handles.editSelectChannelSensitivity = handles.editSelectChannelSensitivity;
fwmodel.handles.textSelectChannelSensitivity =  handles.textSelectChannelSensitivity;

set(fwmodel.handles.editSelectChannelSensitivity,'enable','on');
set(fwmodel.handles.textSelectChannelSensitivity,'enable','on');
set(fwmodel.handles.editSelectChannelSensitivity,'string','0 0');



% --------------------------------------------------------------
function b = isempty_loc(fwmodel)

b = false;
if isempty(fwmodel.Adot)
    b = true;
end

