echo 0 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s1"
echo 1 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s2"
echo 2 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s3"
echo 3 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s4"
echo 4 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s5"
echo 5 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.s6"
echo 6 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d1"
echo 7 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d2"
echo 8 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d3"
echo 9 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d4"
echo 10 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d5"
echo 11 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d6"
echo 12 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d7"
echo 13 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d8"
echo 14 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d9"
echo 15 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d10"
echo 16 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d11"
echo 17 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d12"
echo 18 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d13"
echo 19 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d14"
echo 20 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d15"
echo 21 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
"C:/Users/mz86/Desktop/Fnirs data and analysis/homer2_8/homer2/PACKAGES/tMCimg/bin/Win//tMCimg.exe"  "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw/fw1.d16"
echo 22 > "C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_start"
echo. 2>"C:/Users/mz86/Desktop/Fnirs data and analysis/Experiment 1 - repeat/atlas/fw//.fw_all_stop"
exit
